---
- name: Make directory for packages
  file: path={{ remote_packages_dir }} state=directory

- name: Copy elliptics packages
  copy: src={{ item }} dest="{{ remote_packages_dir }}/"
  with_fileglob:
    - "{{ packages_dir }}/*"

- name: Install elliptics packages
  shell: dpkg --force-depends --install {{ remote_packages_dir }}/*.deb

- name: Install elliptics packages dependencies
  shell: apt-get --fix-broken --assume-yes install
